### ISSUE TITLE
idm更新之后文件名错误了

### ISSUE THREAD

**Issue by EnderAvaritia** [MotooriKashin/ef2#10]
![Snipaste_2022-10-19_18-48-28](https://user-images.githubusercontent.com/84321282/196672122-65fcd06d-3b2e-4cfa-a063-2e42ea80fb7f.png)
![Snipaste_2022-10-19_18-48-49](https://user-images.githubusercontent.com/84321282/196672129-13ef8e99-2a58-47c9-a4d0-7a6494f8abff.png)

**Comment by MotooriKashin** [comment]
怎么个错误法？是依旧“数字文件名”吗？  
能稳定实现吗？比如下另一个文件试试。  
个人经验，B站视频服务器可能会302重定向，IDM会把重定向后的文件名覆盖之前的。可以注意一下下载主机是不是变了，就是bilivideo前面那一串。如果是这样也没办法，这是IDM自己的问题。

**Comment by EnderAvaritia** [comment]
> 怎么个错误法？是依旧“数字文件名”吗？ 能稳定实现吗？比如下另一个文件试试。 个人经验，B站视频服务器可能会302重定向，IDM会把重定向后的文件名覆盖之前的。可以注意一下下载主机是不是变了，就是bilivideo前面那一串。如果是这样也没办法，这是IDM自己的问题。

是数字文件名，在双击之后瞬间显示的是正常是文件名，之后突然变成了数字，猜测？可能是被服务器发送回来的文件名有覆盖了？
我另外随便找了个视频试了试，
![image](https://user-images.githubusercontent.com/84321282/196677853-1776467b-5562-421c-b199-006fc61936bc.png)
下载主机是变了，但是我尝试该回去也是一样的结果。（纯数字）

**Comment by MotooriKashin** [comment]
这就是302重定向了，不信你打开ef2文件看主机是不是和idm显示的不一样。

**Comment by MotooriKashin** [comment]
你提供的这两个下载主机从前缀那乱七八糟的名字都能看出来，都不是主流的CDN服务商，经常搞302重定向往别处这种事。IDM又喜欢自作主张从服务器那里自己获取文件名，一旦碰到重定向文件名必然被覆盖。  
建议下载B站视频手动指定大型CDN服务器，比如金山、腾讯、阿里、华为等……品质保证，能减少被302的几率。相当于主动使用重定向后的服务器。

**Comment by EnderAvaritia** [comment]
> 你提供的这两个下载主机从前缀那乱七八糟的名字都能看出来，都不是主流的CDN服务商，经常搞302重定向往别处这种事。IDM又喜欢自作主张从服务器那里自己获取文件名，一旦碰到重定向文件名必然被覆盖。 建议下载B站视频手动指定大型CDN服务器，比如金山、腾讯、阿里、华为等……品质保证，能减少被302的几率。相当于主动使用重定向后的服务器。

![image](https://user-images.githubusercontent.com/84321282/196684343-6a015f91-d9b2-4c6e-a31b-7f1c007fbbd7.png)
似乎没有被重定向。
有办法禁止使用服务器返回的文件名吗？或者强制指定服务器？

**Comment by MotooriKashin** [comment]
手动替换链接主机就行，获取到了下载链接，那么替换为任意B站名下的服务器都是可用的。比如从你图中的`cn-lnzy...bilivideo.com`替换为`upos-sz-mirrorks3.bilivideo.com`，这是金山的服务器，很可靠。

更多B站视频服务器可参考：  
https://github.com/yujincheng08/BiliRoaming/blob/c33010bc24d769e15de2e7b09529456ffd306888/app/src/main/res/values/strings.xml#L95

**Comment by EnderAvaritia** [comment]
> 手动替换链接主机就行，获取到了下载链接，那么替换为任意B站名下的服务器都是可用的。比如从你图中的`cn-lnzy...bilivideo.com`替换为`upos-sz-mirrorks3.bilivideo.com`，这是金山的服务器，很可靠。
> 
> 更多B站视频服务器可参考： https://github.com/yujincheng08/BiliRoaming/blob/c33010bc24d769e15de2e7b09529456ffd306888/app/src/main/res/values/strings.xml#L95

谢谢。
![image](https://user-images.githubusercontent.com/84321282/196690608-725af8bc-fcd7-4346-8cd1-fe188e4fe2e0.png)
或许根本就没有这个文件吧……

**Comment by MotooriKashin** [comment]
IDM问题，外部没办法处理。关闭。

**Comment by EnderAvaritia** [comment]
好吧。
