### ISSUE TITLE
安装后还是无法下载ef2

### ISSUE THREAD

**Issue by Idealisten** [MotooriKashin/ef2#11]
安装后还是显示IDM目前不支持ef2数据传输协议。或许这是个拼写错误，请检查拼写后重试。IDM版本6.4.1version3

**Comment by MotooriKashin** [comment]
能不能提供你使用的ef2链接样本供分析？

**Comment by JniTaim** [comment]
注册后，如果移动了ef2.exe，就要重新注册

**Comment by ghost** [comment]
> 能不能提供你使用的ef2链接样本供分析？

没什么，我不小心移动了exe文件，可以关闭该Issue了
