### ISSUE TITLE
下载url带空格会自动截取

### ISSUE THREAD

**Issue by yingw** [MotooriKashin/ef2#15]
有些下载链接里面是有空格的，但是也是合法可以下载的，在解析后空格后的内容会被截掉

**Comment by MotooriKashin** [comment]
根据`RFC 3986`，URL中不能包含空格，应转移为`%20`。
而且空格是“定界符，应将其忽略”
```
In some cases, extra whitespace (spaces, line-breaks, tabs, etc.) may
have to be added to break a long URI across lines. The whitespace
should be ignored when the URI is extracted.
```

```
For robustness, software that accepts user-typed URI should attempt
to recognize and strip both delimiters and embedded whitespace.
```

不知道带空格的链接是如何生成的，还是尽量生成标准链接吧。

**Comment by yingw** [comment]
谢谢回复，应该是不标准的文件名造成的，给个例子：
<https://neoclone.screenscraper.fr/api2/mediaJeu.php?devid=jelos&devpassword=jelos&softname=&ssid=derrerr&sspassword=111111&systemeid=4&jeuid=2137&media=support-scan(de)(German Modul)>
这个地址，带空格，会下载一个名为 support-scan(de)(German Modul).png 带空格文件名的文件，虽然标准里是不合法的，但是的确有效。

自己是这样解决的，在URL前后加英文双引号，发现 IDM 也支持，而且就不报错了，filename 不用加
另外 %20 也可以
