### ISSUE TITLE
能不能批量下载

### ISSUE THREAD

**Issue by 10362227** [MotooriKashin/ef2#2]
能不能批量下载

**Comment by MotooriKashin** [comment]
批量下载的话可以生成ef2文件，然后双击该文件下载。  
从浏览器拉起的话，单击一次只能访问一个链接。当然用户脚本代理的话也可以做到一次访问多条链接，然后全部传递给IDM，比如使用一个循环反复调用`window.open`打开链接，当然这样为了避免弹窗过多，请添加`-f`参数，`-q`参数的话我为了提醒用户数据已经发送给IDM了，给了一个弹窗，所以还是会有过多弹窗。  

综上，批量下载还是推荐生成ef2文件，ef2文件能配置的内容跟ef2协议完全一样，只是需要用户保存该文件到本地然后双击打开，这样所有链接都会添加到IDM，别忘了到IDM里“开始队列“。
