### ISSUE TITLE
作者大大，为什么filename超过三个字符后名称变为乱码啊？

### ISSUE THREAD

**Issue by LibertyCola** [MotooriKashin/ef2#3]

**Comment by MotooriKashin** [comment]
印像中不会啊，我Bilibili-Old项目一直在用，视频标题肯定超过3个字。可能是编码转化问题，待明天测试一下再答复。

**Comment by LibertyCola** [comment]
谢谢大佬的回复，已经找到问题了，确实是电脑编码的问题。

MotooriKashin ***@***.***> 于2022年1月9日周日 23:00写道：

**Comment by MotooriKashin** [comment]
经测试ef2文件需要使用utf-8编码，这是IDM官方默认的编码格式，也方便在浏览器端生成。  
你可能是通过Windows自带的记事本手打ef2文件，那么请在保存时将编码从ANSI调整为utf-8。

ps：不推荐手打ef2文件，本功能存在的意义是辅助油猴脚本通过ef2文件进行批量下载。
