### ISSUE TITLE
该ef2文件似乎并不包含有效下载链接！？ 请检查文件内容或者反馈到： https://github.com/MotooriKashin/ef2/issues

### ISSUE THREAD

**Issue by PLA888** [MotooriKashin/ef2#4]
该ef2文件似乎并不包含有效下载链接！？
请检查文件内容或者反馈到：
https://github.com/MotooriKashin/ef2/issues

**Comment by PLA888** [comment]
给他重命名之后就用不了了。

**Comment by MotooriKashin** [comment]
能不能提供该ef2文件以进行测试？github不支持该文件类型可以压缩为zip压缩包再上传。

**Comment by PLA888** [comment]
不好意思，当时的文件我已经粉碎了，出现了那样的情况，我只是重新命名有中文字符就出现提示。










在 2022-02-02 11:36:16，"MotooriKashin" ***@***.***> 写道：

能不能提供该ef2文件以进行测试？github不支持该文件类型可以压缩为zip压缩包再上传。




—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MotooriKashin** [comment]
如果修改的是文件内容的话，注意一下编码格式，只支持UTF-8——我能想到的只有这个原因。

**Comment by PLA888** [comment]
好的，谢谢你。目前能正常使用，我当时只是修改文件名，猜出来的提示可能跟我系统有关。
















在 2022-02-06 21:12:56，"MotooriKashin" ***@***.***> 写道：

如果修改的是文件内容的话，注意一下编码格式，只支持UTF-8——我能想到的只有这个原因。




—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MotooriKashin** [comment]
~_~

**Comment by PLA888** [comment]
考区工作人员：
您好！我是考生戴祖山，2017年高中毕业应征入伍，保留学籍，2019年退役复学，目前大四在校，所提交材料均真实有效，符合相关报考政策。
附上相关情况说明和证明材料。请查收，谢谢。
、
