### ISSUE TITLE
Windows 11 Pro英文系统下界面乱码

### ISSUE THREAD

**Issue by shiyishiaa** [MotooriKashin/ef2#5]
Locale Emulator无法使用，但是功能正常使用，一个无伤大雅的小问题。

![1646087980(1)](https://user-images.githubusercontent.com/39306140/156070475-8a60c046-302f-420e-8ecd-22cafa231b93.png)

**Comment by MotooriKashin** [comment]
的确，本质就是个命令行程序，安装界面也没考虑过编码问题，以后有时间再处理吧。

暂时先关闭了。
