### ISSUE TITLE
ef2文件不支持utf-8编码的格式

### ISSUE THREAD

**Issue by karegyudon** [MotooriKashin/ef2#6]
您好：试用了您发布的工具，非常方便，特别是filename这个扩展很有效的解决了一些下载的问题，但是使用过程中发现如果导出的ef2格式文件为utf-8编码的话，解析到idm中会出现乱码，能否考虑后续对应utf-8编码的文件？

**Comment by MotooriKashin** [comment]
不对啊，IDM默认导出格式就是utf-8，为了与官方保持一致，本工具也只认utf-8格式的文件，反而gbk会乱码才对。（如下图）
![image](https://user-images.githubusercontent.com/60416767/177040993-9f3e41af-413d-4f56-a09f-ee0a309ff321.png)
![image](https://user-images.githubusercontent.com/60416767/177040999-f64f80c3-99cf-4254-8f9f-ca56c6359214.png)
![image](https://user-images.githubusercontent.com/60416767/177041011-2182d6ac-a711-4fe2-9462-ba2bf182f0c2.png)

**Comment by karegyudon** [comment]
你好，我这边尝试了的确是出现类似的问题，是通过双击导出的ef2文件添加下载任务的，添加后IDM里头显示如下：
![Snipaste_2022-07-04_08-08-56](https://user-images.githubusercontent.com/22168767/177062126-f7118a29-c5a1-4f65-8705-8c4f87ac3d94.jpg)
我的IDM版本（正版）：
![Snipaste_2022-07-04_08-09-12](https://user-images.githubusercontent.com/22168767/177062128-d2f3de47-fc7a-4f48-a64a-8d57655fa6f3.jpg)
这个是导出的下载文件。
[bilibili-真田丸.zip](https://github.com/MotooriKashin/ef2/files/9035705/bilibili-.zip)

**Comment by MotooriKashin** [comment]
还真是，已尝试修复，可以去release页面下载试试看
