### ISSUE TITLE
卸载不了会提示“注册失败”

### ISSUE THREAD

**Issue by quanrenxiaohao** [MotooriKashin/ef2#8]
最新版1.0.3，想卸载显示注册失败，重新下载一样显示
![批注 2022-08-24 151105](https://user-images.githubusercontent.com/100709930/186354812-6c2bef02-b43c-41fc-83b3-c1cf7e23ebe6.png)

**Comment by MotooriKashin** [comment]
是不是没有给管理员权限，操作注册表是需要管理员权限的——不过软件应该会检查并弹出管理员权限UAC弹窗才是。  
实在不行直接删除文件就是了，然后使用那些注册表清理工具应该能检查并清理掉，不过放着也没什么关系就是了。

**Comment by quanrenxiaohao** [comment]
> 是没有管理员权限的操作应该是不是软件管理员权限的，不过，并展开管理员UAC弹弹检查。实际上不是直接删除文件就是，然后那些使用给工具清理的工具应该能检查并捡掉，但放着也没什么关系就是了。

有什么办法卸载吗，有点强迫症

**Comment by MotooriKashin** [comment]
看到仓库根目录那个`uninstall.bat`批处理文件吗？下载并以管理员程序运行一下就行——不过还是要管理员权限……注册表这种敏感操作只有管理员才能执行🤣

![image](https://user-images.githubusercontent.com/60416767/186369098-9f5763fa-497e-4d59-8d5e-a5fa66002e4a.png)
