### ISSUE TITLE
有偿定制，加一个验签的小功能

### ISSUE THREAD

**Issue by 23557544** [MotooriKashin/ef2#9]
如题

**Comment by MotooriKashin** [comment]
感谢反馈！不过我不太明白您说的验签是指？验证ef2文件还是ef2链接的签名。  
作为一个本地小工具，又不涉及远程功能，有什么验签的必要吗？  
如果是指将本项目作为其他项目的一部分，只接受来自特定目标的请求。那其实可以直接访问IDM，根本不需要一个中间人来当这个二传手。[IDM](http://www.internetdownloadmanager.com/support/idm_api.html)官方提供了详细的API及代码示例，直接集成进你的代码里，完全不涉及第三方，也就用不着什么验签。

**Comment by 23557544** [comment]
我们是网站应用，需要referer参数，可以直接拉取IDM进行下载吗？
需求可能描述不是很清楚，您说的特定来源是正确的，我们想给您的程序传入一个签名参数进行校验来源，校验通过后再拉起IDM下载。

**Comment by MotooriKashin** [comment]
我总结一下：就是想定制一个二进制文件(.exe)，这个文件**只接受**来自特定网站的请求，校验方式是传递一个签名参数，通过后才拉起IDM，是这样吗？

**Comment by 23557544** [comment]
完全正确，方便的话可以发个联系方式到我的邮箱：hsky@vip.qq.com
